<a href="https://colab.research.google.com/github/Ibraheem101/mlops/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

In [2]:
SEED = 1234

In [4]:
np.random.seed(seed = SEED)
torch.manual_seed(seed = SEED)

### Creating Tensors

In [10]:
x = torch.randn(2, 3)
print(f"Type {x.type()}")
print(f"Size {x.shape}")
print(f"Values \n{(x)}")

Type torch.FloatTensor
Size torch.Size([2, 3])
Values 
tensor([[-0.1549, -1.3706, -0.1319],
        [ 0.8848, -0.2611,  0.6104]])


In [14]:
# Zeros and Ones
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
# List to tensor