<a href="https://colab.research.google.com/github/Ibraheem101/mlops/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

In [2]:
SEED = 1234

In [3]:
np.random.seed(seed = SEED)
torch.manual_seed(seed = SEED)

### Creating Tensors

In [4]:
x = torch.randn(2, 3)
print(f"Type {x.type()}")
print(f"Size {x.shape}")
print(f"Values \n{(x)}")

Type torch.FloatTensor
Size torch.Size([2, 3])
Values 
tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036]])


In [5]:
# Zeros and Ones
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [6]:
# List to tensor
list1 = [[2, 3], [4, 5]]
x = torch.Tensor(list1)
print(f"Type {x.type()}")
print(f"Size {x.shape}")
print(f"Values \n{(x)}")

Type torch.FloatTensor
Size torch.Size([2, 2])
Values 
tensor([[2., 3.],
        [4., 5.]])


In [7]:
# Numpy array to tensor
nparr = np.random.randn(2, 3)
x = torch.Tensor(nparr)
print(f"Type {x.type()}")
print(f"Size {x.shape}")
print(f"Values \n{(x)}")

Type torch.FloatTensor
Size torch.Size([2, 3])
Values 
tensor([[ 0.4714, -1.1910,  1.4327],
        [-0.3127, -0.7206,  0.8872]])


In [8]:
# Changing tensor type
x = torch.Tensor(3, 4)
print(f"Type: {x.type()}")
x = x.long()
print(f"Type: {x.type()}")
x = x.int()
print(f"Type: {x.type()}")
x = x.double()
print(f"Type: {x.type()}")

Type: torch.FloatTensor
Type: torch.LongTensor
Type: torch.IntTensor
Type: torch.DoubleTensor


### Tensor Operations

In [9]:
x = torch.randn(2, 3)
y = torch.randn(2, 3)

z = x + y
print(f"Size {z.shape}")
print(f"Values \n{(z)}")


Size torch.Size([2, 3])
Values 
tensor([[ 0.0761, -0.6775, -0.3988],
        [ 3.0633, -0.1589,  0.3514]])


In [10]:
x = torch.randn(2, 3)
y = torch.randn(2, 3)

z = x + y

print(f"X: {(x)}")
print(f"y: {(y)}")


print(f"Size {z.shape}")
print(f"Z \n{(z)}")

X: tensor([[-0.0098, -1.4473, -0.2039],
        [ 0.8738, -0.6816,  0.6339]])
y: tensor([[ 0.1922,  0.0918, -0.8625],
        [ 0.1596,  0.8184, -0.7649]])
Size torch.Size([2, 3])
Z 
tensor([[ 0.1824, -1.3555, -1.0664],
        [ 1.0333,  0.1368, -0.1310]])


In [11]:
x = torch.randn(2, 3)
y = torch.randn(2, 3)

z = x * y
print(f"Size {z.shape}")
print(f"Z \n{(z)}")

Size torch.Size([2, 3])
Z 
tensor([[ 0.3620, -0.0375, -0.2584],
        [ 0.0221,  1.3691,  0.1772]])


In [12]:
# Matrix Multiplication
x = torch.randn(2, 3)
y = torch.randn(3, 2)

z = torch.mm(x, y)
print(f"Size {z.shape}")
print(f"Z \n{(z)}")

Size torch.Size([2, 2])
Z 
tensor([[ 0.4173,  0.2528],
        [-3.6668, -1.6944]])


In [13]:
# Transpose
x = torch.randn(2, 3)
print(x)
print(torch.t(x))

tensor([[-0.2349, -0.0306,  1.7462],
        [-0.0722, -1.6794, -1.7010]])
tensor([[-0.2349, -0.0722],
        [-0.0306, -1.6794],
        [ 1.7462, -1.7010]])


In [14]:
# Reshaping tensors: Be careful
x = torch.randn(2, 3)
z = x.view(3, 2)
print(x)
print(z)

tensor([[ 0.6486,  1.7653,  1.0812],
        [ 1.2436,  0.8971, -0.0784]])
tensor([[ 0.6486,  1.7653],
        [ 1.0812,  1.2436],
        [ 0.8971, -0.0784]])


In [15]:
# Dimensional operations
x = torch.randn(2, 3)
print(f"Values: \n{x}")
y = torch.sum(x, dim=0) # add each row's value for every column
print(f"Values: \n{y}")
z = torch.sum(x, dim=1) # add each columns's value for every row
print(f"Values: \n{z}")

Values: 
tensor([[ 0.5548, -0.0845,  0.5903],
        [-1.0032, -1.7873,  0.0538]])
Values: 
tensor([-0.4484, -1.8718,  0.6441])
Values: 
tensor([ 1.0607, -2.7367])


### Indexing

In [16]:
x = torch.randn(3, 4)
print (f"x: \n{x}")

x: 
tensor([[ 0.8246, -0.5723, -0.4876,  0.1944],
        [-1.0481, -0.0741, -0.3449, -1.5447],
        [ 0.0685, -1.5104, -1.1706,  0.2259]])


In [17]:
print (f"x[:1]: \n{x[:1]}")
print (f"x[1:3, 2:4]: \n{x[1:3, 2:4]}")

x[:1]: 
tensor([[ 0.8246, -0.5723, -0.4876,  0.1944]])
x[1:3, 2:4]: 
tensor([[-0.3449, -1.5447],
        [-1.1706,  0.2259]])


### Selection

In [18]:
x = torch.randn(3, 3)
print(x)

tensor([[ 1.4696, -1.3284,  1.9946],
        [-0.8209,  1.0061, -1.0664],
        [-0.4572,  0.0901,  0.4018]])


In [19]:
row_index = torch.LongTensor([0, 2])
col_index = torch.LongTensor([0, 2])

selected = torch.index_select(x, dim = 1, index = col_index)
print(selected)

tensor([[ 1.4696,  1.9946],
        [-0.8209, -1.0664],
        [-0.4572,  0.4018]])


In [20]:
selected = x[row_index, col_index] # values from (0, 0) & (1, 2)
print(selected)

tensor([1.4696, 0.4018])


### Joining

In [21]:
x = torch.randn(2, 3)
print (x)
print (x.shape)

tensor([[-1.1542,  0.1192, -0.7348],
        [-1.5864, -0.2671,  2.6874]])
torch.Size([2, 3])


In [22]:
# Concatenation
y = torch.cat([x, x], dim=0) # concat on a specified dimension
print (y)
print (y.shape)

tensor([[-1.1542,  0.1192, -0.7348],
        [-1.5864, -0.2671,  2.6874],
        [-1.1542,  0.1192, -0.7348],
        [-1.5864, -0.2671,  2.6874]])
torch.Size([4, 3])


In [23]:
y = torch.cat([x, x], dim=1) # concat on a specified dimension
print (y)
print (y.shape)

tensor([[-1.1542,  0.1192, -0.7348, -1.1542,  0.1192, -0.7348],
        [-1.5864, -0.2671,  2.6874, -1.5864, -0.2671,  2.6874]])
torch.Size([2, 6])


In [24]:
# Stacking
z = torch.stack([x, x], dim=0) # stack on new dimension
print (z)
print (z.shape)

tensor([[[-1.1542,  0.1192, -0.7348],
         [-1.5864, -0.2671,  2.6874]],

        [[-1.1542,  0.1192, -0.7348],
         [-1.5864, -0.2671,  2.6874]]])
torch.Size([2, 2, 3])


In [25]:
# Stacking
z = torch.stack([x, x], dim=1) # stack on new dimension
print (z)
print (z.shape)

tensor([[[-1.1542,  0.1192, -0.7348],
         [-1.1542,  0.1192, -0.7348]],

        [[-1.5864, -0.2671,  2.6874],
         [-1.5864, -0.2671,  2.6874]]])
torch.Size([2, 2, 3])


### Gradients

In [26]:
x = torch.randn(3, 3, requires_grad=True)

y = 3 * x + 5
z = y.mean()

z.backward() # computes the gradients of z with respect to all tensors that were involved in computing it. In this case, that's just x. The gradients are computed using the chain rule of calculus and stored in x.grad.
print(f"x: \n{x}")
print(f"x.grad: \n{x.grad}") # prints the gradient of x that was computed by the backward() call.

x: 
tensor([[-0.4633,  0.6639,  0.2383],
        [ 0.8305, -0.0838,  0.9523],
        [ 0.2016, -0.1714, -0.8164]], requires_grad=True)
x.grad: 
tensor([[0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333]])


### CUDA

In [27]:
print(torch.cuda.is_available())

False


In [28]:
# Set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print (device)

cpu


In [29]:
x = torch.rand(2,3)
print (x.is_cuda)
x = torch.rand(2,3).to(device) # Tensor is stored on the GPU
print (x.is_cuda)


False
False
